### ISSUE TITLE
regarding some missing files

### ISSUE THREAD

**Issue by Zia-Chowdhury** [USEPA/IO-Model-Builder#11]
model = iomb.make_model('drc.csv',
                            ['satellite_table1.csv', 'satellite_table2.csv'],
                            "sector_meta_data.csv",
                            ['LCIA_factors1.csv', 'LCIA_factors1.csv'])
I would like to know if the files "satellite_table1.csv, satellite_table2.csv, LCIA_factors_factors1.csv, etc." need to be provided or is automatically created by the program. This program is giving many errors mostly regarding missing files.

result = iomb.calculate(model, {'1111a0/oilseed farming/us': 1})
print(result.this_result)
 Also, there is no attribute in the Result class called this_result.

Would appreciate if someone got back to me.

I am running the code in Acanonda Python Spyder.

**Comment by WesIngwersen** [comment]
These files are to be provided by the user. However, examples are provided in the USEEIO framework in the [model build for USEEIOv1.1](https://github.com/USEPA/USEEIO/tree/master/useeiopy/Model%20Builds/USEEIOv1.1)
